### ISSUE TITLE
Trap and give a better error message when _config_override has a bad key

### ISSUE THREAD

**Issue by prestopUCAR** [NCAR/ConfigMaster#19]
```
prestop@asimov:~/GEFS$ ./downloadGFS.py --local_dir ~/tmp/data/
Traceback (most recent call last):
  File "./downloadGFS.py", line 124, in <module>
    p = ConfigMaster(defaultParams, __doc__, add_default_logging=True, allow_extra_parameters=True)
  File "/Users/prestop/git/ConfigMaster/ConfigMaster.py", line 81, in __init__
    self.init(docString, **kwargs)
  File "/Users/prestop/git/ConfigMaster/ConfigMaster.py", line 195, in init
    self.doConfigOverride()
  File "/Users/prestop/git/ConfigMaster/ConfigMaster.py", line 209, in doConfigOverride
    if self.opt[param1] == param1_target:
KeyError: 'model'
```

**Comment by georgemccabe** [comment]
When getting values from a dictionary, you can use the get method instead of the [] operator to get a value and set a default value if the key is not set. The default default is None, so it would not throw an error and instead return None, which you can override with the 2nd argument to get:
`
self.opt.get(param1, 'default_value')`

Another possible solution is to put a try block around the code and catch the KeyError to report a nice error messsage.
```

try:
...
    if self.opt[param1] == param1_target:
...
except KeyError:
    logger.error(f"Key {param1} was not set")
```
